issues3_domain_implementation
alvarogo1998/rss_aggregator pull request #7
Opened 2022-11-16 15:09 UTC by alvarogo1998

## Descripción de la tarea

Implementación del dominio para añadir un rss

## ¿Cómo se ha implementado?

Se ha creado un data class en el cual añadimos el name y la url, después añadimos una interfaz con la función save, y finalmente un SaveRssUseCase con una función execute en la cual guardamos los parámetros.

## Keywords

Model, UseCase, Repository

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2022-11-16 23:57 UTC, HectorMartin4 requested changes
Revisa el codigo

2022-11-16 23:57 UTC, HectorMartin4 commented on app/src/main/java/com/agalobr/rss_aggregator/features/domain/SaveRssUseCase.kt
> +    fun execute (name: String, url: String): Rss? = repository.save(name, url)
Es necesario poner _Rss?_

2022-11-22 15:32 UTC, josem-perram commented on app/src/main/java/com/agalobr/rss_aggregator/features/domain/SaveRssUseCase.kt
> +    fun execute (name: String, url: String): Rss? = repository.save(name, url)
@alvarogo1998 revisa el ticket y fíjate en los parámetros que se envían.

2022-11-22 15:33 UTC, josem-perram requested changes
Revisa los comentarios.

2022-11-22 21:34 UTC, alvarogo1998 commented on app/src/main/java/com/agalobr/rss_aggregator/features/domain/SaveRssUseCase.kt
> +    fun execute (name: String, url: String): Rss? = repository.save(name, url)
He eliminado el rss, y he cambiado en nombre de save a saveRss para que sea mas descriptivo.

2022-11-23 14:27 UTC, HectorMartin4 approved these changes
Ok

2022-11-24 14:43 UTC, merged